# Allow link-deps.mjs to change stuff in the working tree
verifyDepsBeforeRun: warn

allowBuilds:
  nostr-signer-capacitor-plugin: true
  cbor-extract: false
  esbuild: false
  sharp: true
  nostr-signer-capacitor-plugin@https://codeload.github.com/coracle-social/nostr-signer-capacitor-plugin/tar.gz/436adec9ed1e71569748cd56aa697f361e7a8d47: true
  yarn: false
minimumReleaseAgeExclude:
  - '@pomade/core'
  - '@welshman/app'
  - '@welshman/content'
  - '@welshman/editor'
  - '@welshman/feeds'
  - '@welshman/lib'
  - '@welshman/net'
  - '@welshman/domain'
  - '@welshman/signer'
  - '@welshman/store'
  - '@welshman/util'
overrides:
  sharp: ^0.35.3
