allowBuilds:
  nostr-signer-capacitor-plugin: true
  cbor-extract: false
  esbuild: false
  sharp: true
minimumReleaseAgeExclude:
  - '@pomade/core'
  - '@welshman/app'
  - '@welshman/content'
  - '@welshman/editor'
  - '@welshman/feeds'
  - '@welshman/lib'
  - '@welshman/net'
  - '@welshman/router'
  - '@welshman/signer'
  - '@welshman/store'
  - '@welshman/util'
overrides:
  sharp: ^0.35.3
